task 8- add a comment complete
souste/react-front-end-project pull request #5
Opened 2022-12-08 14:14 UTC by Souness1982

2022-12-08 14:43 UTC, HannahBurks requested changes
Looking good so far Stephen! Along with the other stated changes, we need to add something to show what user we are logged in as. It is fine to hardcode this user, but we want to put something on the homepage to signify we are logged in as someone. 

Once these changes are made, please send another PR 😄

2022-12-08 14:43 UTC, HannahBurks commented on src/components/Comments.jsx
>    if (error) return <p>No comments found</p>;
Once posting a comment successfully we want to also have a message displayed telling us the post was successful such as ‘Comment added' 😃

2022-12-08 14:43 UTC, HannahBurks commented on src/components/AddComment.jsx
> +    <form onSubmit={handleSubmit}>
We want to make sure that users aren't able to add blank comments - we will need to add some extra logic to prevent this! 🙂

2022-12-08 14:43 UTC, HannahBurks commented on src/components/AddComment.jsx
> +      <button>Add</button>
We will also want to make sure we are not able to click the post button more than once to prevent multiple posts being sent.

2022-12-08 14:52 UTC, Souness1982 commented
Thanks Hannah, I'll have a look.

2022-12-09 10:58 UTC, yangalexyangg approved these changes
Very good code but looks like I can only write and post one comment before submit button is disabled? I will approve as this meets core functionality but can you make changes?

2022-12-09 11:07 UTC, merged